apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tsa.systemname" . }}-mysql-secret
  namespace: {{ include "tsa.namespace" . }}
  labels:
    {{- include "tsa.labels" . | nindent 4 }}
type: Opaque
data:
  root-password: {{ .Values.mysql.password | printf "%s" | b64enc }}