apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tsa.systemname" . }}-admin-secret
  namespace: {{ include "tsa.namespace" . }}
  labels:
    {{- include "tsa.labels" . | nindent 4 }}
type: Opaque
data:
  root-password: MTIzNDU2Cg==