apiVersion: v1
kind: Service
metadata:
  name: {{ include "tsa.systemname" . }}-mysql
  namespace: {{ include "tsa.namespace" . }}
  labels:
    {{- include "tsa.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "tsa.systemname" . }}-mysql
    {{- include "tsa.labels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
  sessionAffinity: None