apiVersion: v1
kind: Service
metadata:
  name: {{ include "tsa.systemname" . }}-redis
  namespace: {{ include "tsa.namespace" . }}
  labels:
    {{- include "tsa.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "tsa.systemname" . }}-redis
    {{- include "tsa.labels" . | nindent 4 }}
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  type: ClusterIP
  sessionAffinity: None