apiVersion: v1
kind: Service
metadata:
  name: {{ include "tsa.systemname" . }}-web
  namespace: {{ include "tsa.namespace" . }}
  labels:
    {{- include "tsa.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "tsa.systemname" . }}-admin
    tier: front
    {{- include "tsa.labels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: {{ .Values.web.service.type }}
  sessionAffinity: None