apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tsa.systemname" . }}-mysql-cm
  namespace: {{ include "tsa.namespace" . }}
  labels:
    {{- include "tsa.labels" . | nindent 4 }}
data:
  my.conf: |
    bind-address = 0.0.0.0
