apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tsa.systemname" . }}-server
  namespace: {{ include "tsa.namespace" . }}
  labels:
    app: {{ include "tsa.systemname" . }}-server
    tier: backend
    {{- include "tsa.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.server.deploy.replicas }}
  selector:
    matchLabels:
      app: {{ include "tsa.systemname" . }}-server
      tier: backend
      {{- include "tsa.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ include "tsa.systemname" . }}-server
        tier: backend
        {{- include "tsa.labels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ include "tsa.systemname" . }}-server
        image: {{ .Values.global.repository }}/tsa-server-k8s:v1.0.0
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - name: {{ include "tsa.systemname" . }}-server
          protocol: TCP
          containerPort: 8000
        resources:
        {{- with .Values.server.deploy.resources }}
          limits:
            cpu: {{ .limits.cpu | default "1" }}
            memory: {{ .limits.memory | default "2Gi" }}
          requests:
            cpu: {{ .requests.cpu | default "1" }}
            memory: {{ .requests.memory | default "2Gi" }}
        {{- else }}
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "1"
            memory: "2Gi"
        {{- end }}
        env:
        - name: TZ # 设置容器时区
          value: {{ .Values.global.timezone}}
        envFrom:
        - configMapRef:
            name: {{ include "tsa.systemname" . }}-mysql-env
      restartPolicy: {{ .Values.global.restartPolicy }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}