apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-pvc
  namespace: {{ include "tsa.namespace" . }}
  labels:
    {{- include "tsa.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.mysql.pvc.storageClassName }}
  accessModes:
    - {{ .Values.mysql.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.mysql.pvc.storage }}