apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tsa.systemname" . }}-admin-nginx-log-pvc
  namespace: {{ include "tsa.namespace" . }}
  labels:
    {{- include "tsa.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.web.pvc.storageClassName }}
  accessModes:
    - {{ .Values.web.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.web.pvc.storage }}